<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Stage names such as "Rejected", "Withdrawn" or "Disqualified" are the only
     * thing that currently marks a finished, non-hired outcome, and names are
     * neither stable nor translated. The workflow now declares that explicitly:
     * `is_terminal` means no further recruiting action is expected, whether the
     * outcome was positive (`is_hired`) or not.
     */
    public function up(): void
    {
        Schema::table('statuses', function (Blueprint $table): void {
            $table->boolean('is_terminal')->default(false)->after('is_final_stage');
        });

        // A hire has always been a finished outcome; the flag only makes it explicit.
        DB::table('statuses')->where('is_hired', true)->update(['is_terminal' => true]);

        // Pre-launch data fix, run once: workflows generated by
        // `ProvisionDefaultPipeline` and the demo seeder predate both flags, so
        // their known stages would otherwise keep obviously wrong semantics.
        // Names are matched here and never at runtime.
        DB::table('statuses')
            ->where('is_hired', false)
            ->whereIn('name', ['Rejected', 'Withdrawn', 'Disqualified'])
            ->update(['is_terminal' => true, 'is_final_stage' => false]);

        DB::table('statuses')
            ->where('is_hired', false)
            ->where('is_terminal', false)
            ->whereIn('name', ['Offer', 'Approved'])
            ->update(['is_final_stage' => true]);

        // Invariant: a finished outcome is never also an active finalist stage.
        DB::table('statuses')
            ->where('is_terminal', true)
            ->update(['is_final_stage' => false]);
    }

    public function down(): void
    {
        Schema::table('statuses', function (Blueprint $table): void {
            $table->dropColumn('is_terminal');
        });
    }
};
